name: Build and deploy ASP.Net Core app to Azure Web App - EbenezerAPIWIN

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependências
        run: dotnet restore EbenezerConnectApi/EbenezerConnectApi/EbenezerConnectApi.csproj

      - name: Build
        run: dotnet build EbenezerConnectApi/EbenezerConnectApi/EbenezerConnectApi.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish EbenezerConnectApi/EbenezerConnectApi/EbenezerConnectApi.csproj -c Release -o ./publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app

      - name: Login to Azure
        uses: azure/login@v2
       with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3432697D831F4EDFB31E144F206CF13D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CE1C649450DC4312AA97986ABBE013E6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D086AF6C5ECC447DB5E8148948F7443C }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'EbenezerAPIWIN'
          slot-name: 'Production'
          package: .
